name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Set up Node.js
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check for release tag in commit message
        id: check_tag
        run: echo "::set-output name=should_release::$(git log -1 --pretty=%B | grep -c '[release]')"

      - name: Check for previous commits
        id: check_prev_commits
        run: echo "::set-output name=has_previous_commits::$(git rev-list --count HEAD~1)"

      - name: Lint conventional commits
        if: steps.check_tag.outputs.should_release == '1' && steps.check_prev_commits.outputs.has_previous_commits == '1'
        run: npx commitlint --from=HEAD~1 --to=HEAD

      - name: Create release
        if: steps.check_tag.outputs.should_release == '1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          PAT: ${{ secrets.PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          npx lerna version --conventional-commits --yes
          npx lerna publish from-package --yes --registry=https://registry.npmjs.org/
